import 'bootstrap/dist/css/bootstrap.css'
import "./globals.css";
import BootstrapClient from '../../components/BootstrapClient';
import Navbar from '../../components/Navbar';
import { Poppins } from 'next/font/google';


const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
